BASE_TASK_CONFIG_PATH: habitat_extensions/config/zs_vlnce_task.yaml
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
TORCH_GPU_IDS: [0]
GPU_NUMBERS: 1
NUM_ENVIRONMENTS: 8
TENSORBOARD_DIR: data/tensorboard_dirs/
CHECKPOINT_FOLDER: data/checkpoints/
EVAL_CKPT_PATH_DIR: data/checkpoints/
RESULTS_DIR: data/logs/eval_results/
VIDEO_DIR: data/logs/video/
KEYBOARD_CONTROL: 1

SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']

MAP:
  VISUALIZE: True
  PRINT_IMAGES: True

EVAL:
  USE_CKPT_CONFIG: False
  SAVE_RESULTS: False
  SPLIT: val_unseen